index:
    path: /
    controller: App\Controller\ProStagesController::index

entreprises:
    path: /entreprises/
    controller: App\Controller\ProStagesController::entreprises

formations:
    path: /formations/
    controller: App\Controller\ProStagesController::formations

stages:
    path: /stages/{id}
    controller: App\Controller\ProStagesController::stages

entreprise:
    path: /entreprise/{id}
    controller: App\Controller\ProStagesController::entreprise

formation:
    path: /formation/{id}
    controller: App\Controller\ProStagesController::formation

ajouterEntreprise:
    path: /ajouterEntreprise/
    controller: App\Controller\ProStagesController::ajouterEntreprise

modifierEntreprise:
    path: /modifierEntreprise/{id}
    controller: App\Controller\ProStagesController::modifierEntreprise